### ISSUE TITLE
Crash on Game Load

### ISSUE THREAD

**Issue by WenXin20** [MinecraftModDevelopmentMods/CommunityMod#81]
Forge v14.23.5.2821
Community Mod v1.0.83
I got this crash while trying to load the game.
[Crash Log](https://gist.github.com/WenXin20/501bb4e3482d718a00ada92d581d6d22)

**Comment by antoinegag** [comment]
@gegy1000 I think this is you

**Comment by itsmeow** [comment]
https://github.com/MinecraftModDevelopmentMods/CommunityMod/blob/master/src/main/java/com/mcmoddev/communitymod/gegy/squashable/SquashableMod.java

**Comment by twilight-sparkle-irl** [comment]
Still broken on latest curseforge build

**Comment by antoinegag** [comment]
@no-boot-device same error? Can you provide a crashlog or something? 

Also I think this mod is pretty much unmaintained at this point so chances that there will be a fix are slim

**Comment by KiriCattus** [comment]
Just asked Dark if he can help me get back on top of things here so maybe soon:tm:
Also yes a crash log will be helpful even if it's the same kind as the above :)

**Comment by twilight-sparkle-irl** [comment]
I'm personally fine with disabling squishing by default as a fix, I just wanted to see what it was like.
But yes, [here's the crashlog](https://paste.ee/p/l87h5)

**Comment by KiriCattus** [comment]
Might be a good idea for now but I'll see if I can find some time later to get setup and look at this, once I prod @Darkhax again for access that is xD thanks for the log though

**Comment by antoinegag** [comment]
@ProxyNeko Why re-open this issue? @no-boot-device's issue is different. I think they should open a new one.

**Comment by KiriCattus** [comment]
Because that way I see this when I check the issues soon:tm: I don't mind if it's in this ticket or a new one.
