### ISSUE TITLE
[Suggestion] Add a wiki

### ISSUE THREAD

**Issue by linxuanm** [MinecraftModDevelopmentMods/CommunityMod#87]
Is it possible to add a wiki-ish page that everyone can contribute to and write a brief summary on what their sub mod does?
There are a lot of content in the mod; however, players (and other contributors too) might find it easier to utilize the mod in-game to its full potential if there is a wiki. As an example, complex sub mods like "Routiduct" may be hard to understand and use if no guides/introductions were given.
To contributors, a wiki may be handy so they can understand what other contributors are doing and might be able to provide integrations with other contributors' sub mods.

**Comment by ErdbeerbaerLP** [comment]
Great idea! (And I also want to know what a routiduct does)

**Comment by antoinegag** [comment]
Do Github wikis allow for external contributors? If so we can use that. If not we can make a `wiki` or `doc` directory and use markdown files. PRs welcome!

**Comment by linxuanm** [comment]
> Do Github wikis allow for external contributors?

I think so. This is probably configurable in the project settings.

EDIT: Yep: [https://help.github.com/en/articles/changing-access-permissions-for-wikis](https://help.github.com/en/articles/changing-access-permissions-for-wikis)

**Comment by antoinegag** [comment]
@darkhax think you could enable that?

**Comment by Darkhax** [comment]
Should now be open @antoinegag

**Comment by davidmaamoaix** [comment]
Thanks.
Is it possible to add a link to the wiki in the README or Curseforge page (to acknowledge contributors and players)?

**Comment by antoinegag** [comment]
I also added a link to the curseforge page

**Comment by Darkhax** [comment]
Cool, I think we can close this then?
