### ISSUE TITLE
Latest curseforge build crashes

### ISSUE THREAD

**Issue by LegendaryGeek** [MinecraftModDevelopmentMods/CommunityMod#96]
https://gist.github.com/LegendaryGeek/9073f8c48cf815ca1e61d152af05964b

^^^ Report ^^^
I downloaded the latest build today and it crashed upon startup

**Comment by antoinegag** [comment]
https://github.com/MinecraftModDevelopmentMods/CommunityMod/blob/7daf20b91dced084a106c2de6d420dac5f17f774/src/main/java/com/mcmoddev/communitymod/commoble/ants/SubmodAnts.java#L12

@Commoble

**Comment by JamiesWhiteShirt** [comment]
You need to update Forge. The project currently compiles with 14.23.5.2824

**Comment by antoinegag** [comment]
Woops
