### ISSUE TITLE
Java Runtime Exception Crash

### ISSUE THREAD

**Issue by WenXin20** [MinecraftModDevelopmentMods/CommunityMod#98]
Forge v14.23.5.2825
Community Mod v1.0.92
I get this crash whenever I tried to load the game. But if I turn `B:extrarandomness=false`, the game doesn't crash. This has been happening for a while now and I just found out it has something to do with the Extra Randomness module.
[Crash Report](https://gist.github.com/WenXin20/4c8d07b5e4bf2614dafe3952f7552f8a)

**Comment by Darkhax** [comment]
Could you try updating to a newer version of Java? The log shows that you're using is `1.8.0_51-b16` and the latest version is `1.8.0_202`. Make sure you are launching the game with the newer version and it shows the newer version on the F3 screen. 

There is also a chance that this issue could be related to bad RAM in your system. I would recommend doing a really simple test to check for issues. If you're using Windows you should already have the `Windows Memory Diagnostic tool` available which you can do to check for system issues.

**Comment by WenXin20** [comment]
Updating to the latest Java didn't fix it and the Memory Diagnostic tool didn't find anything wrong.
