### ISSUE TITLE
[Suggestion] Chicken arrows

### ISSUE THREAD

**Issue by DWX12** [MinecraftModDevelopmentMods/CommunityMod#99]
Be able to pick up or catch chickens and use them as arrows, which may or may not kill the chicken upon impact and will always produce one chicken egg.

https://c8.alamy.com/comp/BPED3B/charlie-sheen-hot-shots!-part-deux-1993-BPED3B.jpg

**Comment by KiriCattus** [comment]
I like this idea, I'll see if I can get anyone else to take a look at it sadly I think it's currently out of my reach :/
